
language: python
services:
- docker
install:
- make deps
script:
- make test
- make lint
- make docker_build
- make docker_push
- make test_xunit
deploy:
    provider: heroku
    app: young-refuge-79447
    api_key: ${HEROKU_API_KEY}